# Generated by Django 5.0.1 on 2025-03-21 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('mission_title', models.CharField(default='Our Mission', max_length=255)),
                ('mission_description', models.TextField()),
            ],
            options={
                'db_table': 'about_us',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(upload_to='admin/profile_pics/')),
                ('about_us', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='CustomizeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(upload_to='organizer/customize_event_cover_images/')),
            ],
            options={
                'db_table': 'customize_events',
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255)),
                ('cat_image', models.ImageField(default='', upload_to='category_pics/')),
                ('cat_desc', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'event_category',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(upload_to='organizer/profile_pics/')),
                ('company_logo', models.ImageField(upload_to='organizer/company_logo/')),
                ('about_us', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'organizer',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(upload_to='profile_pics/')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='CustomizeEventTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='organizer/event_theme/')),
                ('price', models.CharField(max_length=10)),
                ('customize_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customize_event_pics', to='myapp.customizeevent')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_tickets', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('state', models.CharField(default='Andhra Pradesh', max_length=40)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='organizer/event_cover_images/')),
                ('is_approved', models.BooleanField(default=False)),
                ('event_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='myapp.eventcategory')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='myapp.organizer')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='EventPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='organizer/event_images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_pics', to='myapp.event')),
            ],
        ),
        migrations.AddField(
            model_name='customizeevent',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customize_events', to='myapp.organizer'),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amt', models.CharField(max_length=255)),
                ('no_of_tickets', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_id', to='myapp.event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='EventTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('no_of_tickets', models.CharField(max_length=1)),
                ('total_amount', models.CharField(max_length=6)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='myapp.event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='myapp.user')),
            ],
            options={
                'db_table': 'event_tickets',
            },
        ),
    ]
